2024-11-28 22:48:21,477 - ERROR: ETL Process Error: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'testingtable'. (208) (SQLExecDirectW)")
[SQL: SELECT COUNT(*) as total FROM (SELECT * FROM testingtable) subquery]
(Background on this error at: https://sqlalche.me/e/20/f405)
